---
#
# Test ball valve
#

########################
# Mandatory part ....
########################
substitutions:
  label: esp32a
  system_name: ball-valve-1
  system_id: ball_valve_1
  friendly_name: Ball valve 1
  description: Test ball valve controller with CR05 feedback wiring
  encryption_key: !secret esphome_encryption_key
  ota_password: !secret esphome_ota_password

packages:
  device: !include devices/ball_valve_ctrl_esp32c3.yaml
  ########################
  # Optional part ... include below components and sensors as needed
  ########################
  i2c: !include components/i2c_ball_valve_ctrl_esp32c3.yaml
  dallas: !include components/1wire_ball_valve_ctrl_esp32c3.yaml

sensor: 
  - <<: !include sensors/htu21d.yaml
  - platform: dallas_temp
    name: "${friendly_name} upper 1-wire"
    id: ${system_id}_temperature_upper
    one_wire_id: wire_tx
    #dallas_id: wire_tx
    #address:  # only one sensor per wire - so none needed
  - platform: dallas_temp
    name: "${friendly_name} lower 1-wire"
    id: ${system_id}_temperature_lower
    one_wire_id: wire_rx
    #allas_id: wire_rx
    #address:  # only one sensor per wire - so none needed

