---
#
# IR blaster generic IO pcb with CO2 + dallas + PIR sensors + i2c sensors
#

substitutions:
  label: esp32b
  system_name: io-test-1
  system_id: io_test_1
  friendly_name: IO test 1
  description: Generic IO with IR blaster, I2C and CO2 sensors
  encryption_key: !secret esphome_encryption_key
  ota_password: !secret esphome_ota_password

packages:
  device: !include devices/hp_genio_esp32c3.yaml
  i2c: !include components/i2c_hp_genio_esp32c3.yaml
  dallas: !include components/1wire_hp_genio_esp32c3.yaml

esphome:
  platformio_options:
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"
      - "-DARDUINO_USB_MODE=1"  
      
uart:
  id: hpuart_esp32c3
  rx_pin: GPIO20
  tx_pin: GPIO21
  baud_rate: 2400

sensor: 
  - <<: !include sensors/htu21d.yaml
  - <<: !include sensors/tsl2561.yaml
  - <<: !include sensors/mhz19.yaml
  - <<: !include sensors/dallas-x1.yaml

binary_sensor:
  - platform: gpio
    device_class: motion
    id: ${system_id}_pir_sensor
    name: "${friendly_name} movement sensor"
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: true
