---
#
# Test ball valve
#

substitutions:
  label: esp32b
  system_name: io-test-1
  system_id: io_test_1
  friendly_name: IO test 1
  description: Generid IO with IR blaster, I2C and CO2 sensors
  encryption_key: !secret esphome_encryption_key
  ota_password: !secret esphome_ota_password

packages:
  device: !include devices/ir_generic_io.yaml
  i2c: !include components/i2c_esp32c3_pcbs.yaml
  dallas: !include components/1wire_ir_io_pcb.yaml

uart:
  rx_pin: GPIO20
  tx_pin: GPIO21
  baud_rate: 9600

sensor: 
  - <<: !include sensors/htu21d.yaml
  - <<: !include sensors/tsl2561.yaml
  - <<: !include sensors/mhz19.yaml
  - platform: dallas
    name: "${friendly_name} 1-wire sensor"
    id: ${system_id}_temperature_1wire
    # dallas_id: wire_5
    index: 0 # only one sensor per wire - so index is safe

binary_sensor:
  - platform: gpio
    device_class: motion
    id: ${system_id}_pir_sensor
    name: "${friendly_name} movement sensor"
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: true
