---
# Seeed Studio XIAO ESP32C6
#
# https://docs.platformio.org/en/latest/boards/espressif32/seeed_xiao_esp32c6.html
#
esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf # or arduino # alternatively
    version: recommended

substitutions:
  generic_irled_out_pin: GPIO2
  generic_statusled_out_pin: GPIO20
  i2c_sda_pin: GPIO22
  i2c_scl_pin: GPIO23
  uart1_rx_pin: GPIO17
  uart1_tx_pin: GPIO16
  # for generic use
  onewire_pin1: GPIO18
  onewire_pin2: GPIO21
