---
# ESPHome Core configuration
#
# Sets the defaults for the main core configuration of my ESPHome devices.
#
# https://esphome.io/components/esphome.html
#
esphome:
  name: "esp-${system_name}"
  comment: "${description}"
  build_path: "./.build/${system_name}/"
  # platformio_options:
  #   # board_build.flash_mode: dio
  #   board_build.extra_flags:
  #     - "-DARDUINO_USB_CDC_ON_BOOT=0"
  #     # - "-DARDUINO_USB_MODE=1"  

preferences:
  flash_write_interval: 86400s
