---
# Wi-Fi component package
#
# Contains my common Wi-Fi setup.
#
# https://esphome.io/components/wifi.html
#
substitutions:
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_ap_password: !secret wifi_password

wifi:
  id: ${system_id}_wifi
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"
  reboot_timeout: 10min

  ap:
    ssid: "${friendly_name}"
    password: "${wifi_ap_password}"
  on_connect:
    - delay: 10s 

sensor:
  - <<: !include ../sensors/wifi_signal.yaml

text_sensor:
  - <<: !include ../text_sensors/version.yaml
  - <<: !include ../text_sensors/wifi_info.yaml
